name: Badminton Bookings

on:
  schedule:
    - cron: '0 0 * * *' # This runs the script daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4' # Specify the Python version

    - name: Install libraries
      run: |
          apt-get update -qq -y
          apt-get install -y wget unzip fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0
          libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 libu2f-udev libvulkan1 libxcomposite1
          libxdamage1 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils   
      
    - name: Install Chrome
      run: |
          wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb
          sudo dpkg -i google-chrome-stable_114.0.5735.90-1_amd64.deb || sudo apt-get install -f -y
          google-chrome --version

    - name: Install ChromeDriver
      run: |
          # Set the ChromeDriver version corresponding to Chrome 114
          CHROME_DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_114.0.5735")
          wget "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
          sudo apt-get install -y unzip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        DISPLAY: ':99' # Set display environment variable for headless mode
      run: |
        # Start Xvfb (X virtual framebuffer) for headless mode
        Xvfb :99 -ac &
        python booking.py # Replace 'your_script.py' with your file name
